name: Build MacSpoof
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AnemoneTweaks/theos-action@master
        with:
          theos-src: https://github.com/theos/theos.git
      - run: make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: MacSpoof-deb
          path: packages/*.deb
